const tasks = [
  // 🔥 Top 20 Most Important (for interviews & real-world skills)
  "1. To-Do App with CRUD Operations (local dummy API or json-server)",
  "2. Todo List with Real API Integration (fetch, add, edit, delete tasks)",
  "3. State Management with Context API (global state for user auth and theme toggle with persistence)",
  "4. Shopping Cart with Redux or Context API (global state management)",
  "5. Authentication Flow with Protected Routes (login/logout with React Router and Context API)",
  "6. React Router with Nested Routes (multi-page app with route hierarchy)",
  "7. Form with Validation using React Hook Form (custom validations)",
  "8. React Table with Sorting & Filtering (dynamic column sorting/filtering)",
  "9. Search & Filter Component with Debounce (optimized search input)",
  "10. Complex Local State Management with useReducer (multi-step form/shopping cart)",
  "11. Custom Hook for Data Fetching with Caching (loading/error states and cache)",
  "12. Pagination UI with API or Manual Data (page-wise data display)",
  "13. Infinite Scroll with Load More on Scroll (load items on scroll end)",
  "14. Tabs Component (dynamic tabs switching content)",
  "15. Modal Component (reusable modal with controlled open/close state)",
  "16. Custom Dropdown/Select Component (reusable with optional search)",
  "17. Drag-and-Drop List (using react-beautiful-dnd or pure JS)",
  "18. File Upload with Progress Bar (show real-time upload progress)",
  "19. Optimizing Expensive Calculations with useMemo (heavy computation optimization)",
  "20. Dynamic Form Builder (fields change dynamically with validation)",

  // ✨ Nice to Have / Advanced or Less Frequently Asked
  "21. Debounced Search with API Integration (responsive search with API calls)",
  "22. Infinite Scroll with API Pagination and Memoization (optimized with useMemo)",
  "23. Accordion Component (expand/collapse individual items)",
  "24. Collapsible Sidebar Menu (collapsible menu with smooth animations)",
  "25. Drag and Drop with State Persistence (state saved with Context/Redux on reload)",
  "26. User Profile Page with API Data Fetching (display user data)",
  "27. Optimized List Rendering with Virtualization (react-window/react-virtualized)",
  "28. Countdown Timer (using useState and useEffect)",
];
